version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '5454:5432'
    volumes:
      - ./data:/data/pg-db
    container_name: presence
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
